-- Auto-generated from schema-map-postgres.yaml (map@sha1:F0EE237771FBA8DD7C4E886FF276F91A862C3718)
-- engine: postgres
-- table:  encryption_policies

CREATE TABLE IF NOT EXISTS encryption_policies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  policy_name VARCHAR(100) NOT NULL UNIQUE,
  mode TEXT NOT NULL,
  layer_selection TEXT NOT NULL DEFAULT 'defined',
  min_layers SMALLINT NOT NULL DEFAULT 1,
  max_layers SMALLINT NOT NULL DEFAULT 3,
  aad_template JSONB NULL,
  notes TEXT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_enc_mode CHECK (mode IN ('local','kms','multi-kms')),
  CONSTRAINT chk_enc_layer_selection CHECK (layer_selection IN ('defined','round_robin','random','hash_mod'))
);
